In [2]:
import pandas as pd

In [6]:
df = pd.read_excel('coordenadas_trafico.xlsx', skiprows=1)
df.head()

,Id,Vialidad,Inicio,Destino,Coordenadas inicio,ini_lat,ini_lon,Coordenadas destino,dest_lat,dest_lon
0,1,Av. Insurgentes,Av. Benjamín Franklin,Av. Chapultepec,"19.403703153280865, -99.16926996113284",19.403703,-99.169270,"19.4229921001133, -99.16315227550801",19.422992,-99.163152
1,2,Av. Nuevo León,Av. Benjamín Franklin,Laredo,"19.403542470698824, -99.17115305982682",19.403542,-99.171153,"19.413142121368157, -99.17160611799854",19.413142,-99.171606
2,3,Av. Chapultepec,Av. Veracruz,Av. Insurgentes,"19.420340877334226, -99.17672176573215",19.420341,-99.176722,"19.423442370678924, -99.16421684905984",19.423442,-99.164217
3,4,Av. Oaxaca,Av. Sonora,Av. Chapultepec,"19.416052295205603, -99.16986030171391",19.416052,-99.169860,"19.423174342726682, -99.16352664262013",19.423174,-99.163527
4,5,Cto. Bicentenario,Av. Benjamín Franklin,Av. Chapultepec,"19.408068338628578, -99.18417193532242",19.408068,-99.184172,"19.42043660332917, -99.17781797602458",19.420437,-99.177818

In [11]:
# drop column id
df.drop('Destino', axis=1, inplace=True)

In [12]:
df.head()

            Vialidad    ini_lat    ini_lon   dest_lat   dest_lon
0    Av. Insurgentes  19.403703 -99.169270  19.422992 -99.163152
1     Av. Nuevo León  19.403542 -99.171153  19.413142 -99.171606
2    Av. Chapultepec  19.420341 -99.176722  19.423442 -99.164217
3         Av. Oaxaca  19.416052 -99.169860  19.423174 -99.163527
4  Cto. Bicentenario  19.408068 -99.184172  19.420437 -99.177818

In [17]:
df_rename = df.rename(columns={'ini_lat': 'x1', 'ini_lon': 'y1', 'dest_lat': 'x2', 'dest_lon': 'y2'})

In [18]:
df_rename.head()

            Vialidad         x1         y1         x2         y2
0    Av. Insurgentes  19.403703 -99.169270  19.422992 -99.163152
1     Av. Nuevo León  19.403542 -99.171153  19.413142 -99.171606
2    Av. Chapultepec  19.420341 -99.176722  19.423442 -99.164217
3         Av. Oaxaca  19.416052 -99.169860  19.423174 -99.163527
4  Cto. Bicentenario  19.408068 -99.184172  19.420437 -99.177818

In [20]:
# save to csv
df_rename.to_csv('coordenadas_trafico.csv', index=False)