In [48]:
import pandas as pd

In [49]:
df = pd.read_excel('coordenadas_trafico.xlsx', skiprows=1)
df.head()

,Id,Vialidad,Inicio,Destino,Coordenadas inicio,ini_lat,ini_lon,Coordenadas destino,dest_lat,dest_lon
0,1,Av. Insurgentes,Av. Benjamín Franklin,Av. Chapultepec,"19.403703153280865, -99.16926996113284",19.403703,-99.169270,"19.4229921001133, -99.16315227550801",19.422992,-99.163152
1,2,Av. Nuevo León,Av. Benjamín Franklin,Laredo,"19.403542470698824, -99.17115305982682",19.403542,-99.171153,"19.413142121368157, -99.17160611799854",19.413142,-99.171606
2,3,Av. Chapultepec,Av. Veracruz,Av. Insurgentes,"19.420340877334226, -99.17672176573215",19.420341,-99.176722,"19.423442370678924, -99.16421684905984",19.423442,-99.164217
3,4,Av. Oaxaca,Av. Sonora,Av. Chapultepec,"19.416052295205603, -99.16986030171391",19.416052,-99.169860,"19.423174342726682, -99.16352664262013",19.423174,-99.163527
4,5,Cto. Bicentenario,Av. Benjamín Franklin,Av. Chapultepec,"19.408068338628578, -99.18417193532242",19.408068,-99.184172,"19.42043660332917, -99.17781797602458",19.420437,-99.177818

In [50]:
# drop column id
df.drop('Destino', axis=1, inplace=True)

In [51]:
df.head()

,Id,Vialidad,Inicio,Coordenadas inicio,ini_lat,ini_lon,Coordenadas destino,dest_lat,dest_lon
0,1,Av. Insurgentes,Av. Benjamín Franklin,"19.403703153280865, -99.16926996113284",19.403703,-99.169270,"19.4229921001133, -99.16315227550801",19.422992,-99.163152
1,2,Av. Nuevo León,Av. Benjamín Franklin,"19.403542470698824, -99.17115305982682",19.403542,-99.171153,"19.413142121368157, -99.17160611799854",19.413142,-99.171606
2,3,Av. Chapultepec,Av. Veracruz,"19.420340877334226, -99.17672176573215",19.420341,-99.176722,"19.423442370678924, -99.16421684905984",19.423442,-99.164217
3,4,Av. Oaxaca,Av. Sonora,"19.416052295205603, -99.16986030171391",19.416052,-99.169860,"19.423174342726682, -99.16352664262013",19.423174,-99.163527
4,5,Cto. Bicentenario,Av. Benjamín Franklin,"19.408068338628578, -99.18417193532242",19.408068,-99.184172,"19.42043660332917, -99.17781797602458",19.420437,-99.177818

In [52]:
df_rename = df.rename(columns={'ini_lat': 'x1', 'ini_lon': 'y1', 'dest_lat': 'x2', 'dest_lon': 'y2'})

In [53]:
df_rename.head()

,Id,Vialidad,Inicio,Coordenadas inicio,x1,y1,Coordenadas destino,x2,y2
0,1,Av. Insurgentes,Av. Benjamín Franklin,"19.403703153280865, -99.16926996113284",19.403703,-99.169270,"19.4229921001133, -99.16315227550801",19.422992,-99.163152
1,2,Av. Nuevo León,Av. Benjamín Franklin,"19.403542470698824, -99.17115305982682",19.403542,-99.171153,"19.413142121368157, -99.17160611799854",19.413142,-99.171606
2,3,Av. Chapultepec,Av. Veracruz,"19.420340877334226, -99.17672176573215",19.420341,-99.176722,"19.423442370678924, -99.16421684905984",19.423442,-99.164217
3,4,Av. Oaxaca,Av. Sonora,"19.416052295205603, -99.16986030171391",19.416052,-99.169860,"19.423174342726682, -99.16352664262013",19.423174,-99.163527
4,5,Cto. Bicentenario,Av. Benjamín Franklin,"19.408068338628578, -99.18417193532242",19.408068,-99.184172,"19.42043660332917, -99.17781797602458",19.420437,-99.177818

In [61]:
# quitar , a todos los elementos de x1, y1, x2, y2 si no son nan
df_rename['x1'] = df_rename['x1'].apply(lambda x: x.replace(',', '') if not type(x) == float else x)

In [62]:
# utrn x1, y1, x2, y2 to float
df_rename['x1'] = df_rename['x1'].astype(float)
df_rename['y1'] = df_rename['y1'].astype(float)
df_rename['x2'] = df_rename['x2'].astype(float)
df_rename['y2'] = df_rename['y2'].astype(float)

In [63]:
df_rename.head()

,Id,Vialidad,Inicio,Coordenadas inicio,x1,y1,Coordenadas destino,x2,y2
0,1,Av. Insurgentes,Av. Benjamín Franklin,"19.403703153280865, -99.16926996113284",19.403703,-99.169270,"19.4229921001133, -99.16315227550801",19.422992,-99.163152
1,2,Av. Nuevo León,Av. Benjamín Franklin,"19.403542470698824, -99.17115305982682",19.403542,-99.171153,"19.413142121368157, -99.17160611799854",19.413142,-99.171606
2,3,Av. Chapultepec,Av. Veracruz,"19.420340877334226, -99.17672176573215",19.420341,-99.176722,"19.423442370678924, -99.16421684905984",19.423442,-99.164217
3,4,Av. Oaxaca,Av. Sonora,"19.416052295205603, -99.16986030171391",19.416052,-99.169860,"19.423174342726682, -99.16352664262013",19.423174,-99.163527
4,5,Cto. Bicentenario,Av. Benjamín Franklin,"19.408068338628578, -99.18417193532242",19.408068,-99.184172,"19.42043660332917, -99.17781797602458",19.420437,-99.177818

In [64]:
# save to csv
df_rename.to_csv('coordenadas_trafico.csv', index=False)